image: java:8

stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  image: maven:3-jdk-8
  script: "mvn package -B"

deploy_dev:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_API_DEV --api-key=$HEROKU_API_KEY
  only:
    - develop
  tags:
    - docker
